"""Add payment tracking tables for locker rentals and strata-owned lots.

Revision ID: 026
Revises: 025
Create Date: 2026-06-03
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "026"
down_revision = "025"
branch_labels = None
depends_on = None


def upgrade():
    # Payment configuration (singleton, id=1)
    op.execute("""
        CREATE TABLE payment_config (
            id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
            advance_notice_days INTEGER NOT NULL DEFAULT 45,
            additional_reminder_days INTEGER[] NOT NULL DEFAULT '{30,14,7}',
            past_due_notice_days INTEGER[] NOT NULL DEFAULT '{1,7,14,30}',
            late_fee_amount NUMERIC(10,2),
            grace_period_days INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
    """)

    # Payment schedules
    op.execute("""
        CREATE TYPE paymentfrequency AS ENUM ('monthly', 'quarterly', 'yearly');
    """)
    op.execute("""
        CREATE TABLE payment_schedules (
            id SERIAL PRIMARY KEY,
            lot_id INTEGER NOT NULL REFERENCES lots(id) ON DELETE CASCADE,
            party_id INTEGER NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
            description TEXT NOT NULL,
            amount NUMERIC(10,2) NOT NULL,
            frequency paymentfrequency NOT NULL DEFAULT 'monthly',
            billing_day INTEGER NOT NULL DEFAULT 1 CHECK (billing_day BETWEEN 1 AND 31),
            start_date DATE NOT NULL,
            end_date DATE,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
    """)
    op.execute("CREATE INDEX ix_payment_schedules_lot ON payment_schedules(lot_id);")
    op.execute("CREATE INDEX ix_payment_schedules_party ON payment_schedules(party_id);")
    op.execute("CREATE INDEX ix_payment_schedules_active ON payment_schedules(is_active);")

    # Payment records (generated by scheduler, manually recordable)
    op.execute("""
        CREATE TYPE paymentstatus AS ENUM (
            'pending', 'paid', 'overdue', 'partially_paid', 'cancelled'
        );
    """)
    op.execute("""
        CREATE TYPE paymentmethod AS ENUM (
            'cash', 'cheque', 'etransfer', 'direct_deposit', 'credit_card', 'other'
        );
    """)
    op.execute("""
        CREATE TABLE payments (
            id SERIAL PRIMARY KEY,
            payment_schedule_id INTEGER NOT NULL REFERENCES payment_schedules(id) ON DELETE CASCADE,
            lot_id INTEGER NOT NULL REFERENCES lots(id) ON DELETE CASCADE,
            party_id INTEGER NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
            amount_due NUMERIC(10,2) NOT NULL,
            amount_paid NUMERIC(10,2) NOT NULL DEFAULT 0,
            due_date DATE NOT NULL,
            paid_date DATE,
            status paymentstatus NOT NULL DEFAULT 'pending',
            payment_method paymentmethod,
            reference_number TEXT,
            notes TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
    """)
    op.execute("CREATE INDEX ix_payments_schedule ON payments(payment_schedule_id);")
    op.execute("CREATE INDEX ix_payments_lot ON payments(lot_id);")
    op.execute("CREATE INDEX ix_payments_party ON payments(party_id);")
    op.execute("CREATE INDEX ix_payments_status ON payments(status);")
    op.execute("CREATE INDEX ix_payments_due_date ON payments(due_date);")

    # Payment notification log
    op.execute("""
        CREATE TYPE paymentnotificationtype AS ENUM (
            'advance_notice', 'reminder', 'overdue_notice', 'manual'
        );
    """)
    op.execute("""
        CREATE TABLE payment_notifications (
            id SERIAL PRIMARY KEY,
            payment_id INTEGER NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
            notification_type paymentnotificationtype NOT NULL,
            recipient_email TEXT NOT NULL,
            sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            status TEXT NOT NULL DEFAULT 'sent'
        );
    """)
    op.execute("CREATE INDEX ix_payment_notifications_payment ON payment_notifications(payment_id);")
    op.execute("CREATE INDEX ix_payment_notifications_type ON payment_notifications(notification_type);")

    # Seed default config
    op.execute("""
        INSERT INTO payment_config (id) VALUES (1);
    """)


def downgrade():
    op.execute("DROP TABLE IF EXISTS payment_notifications;")
    op.execute("DROP TYPE IF EXISTS paymentnotificationtype;")
    op.execute("DROP TABLE IF EXISTS payments;")
    op.execute("DROP TYPE IF EXISTS paymentmethod;")
    op.execute("DROP TYPE IF EXISTS paymentstatus;")
    op.execute("DROP TABLE IF EXISTS payment_schedules;")
    op.execute("DROP TYPE IF EXISTS paymentfrequency;")
    op.execute("DROP TABLE IF EXISTS payment_config;")
